<?php

/**
 * PluginUpdateNotificationRequestTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginUpdateNotificationRequestTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return object PluginUpdateNotificationRequestTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('PluginUpdateNotificationRequest');
  }
}
