pc:
  updateNotification:
    caption: "Update Notification"
    configurable: false
    sample:
      en:
        - "[{{ op_config.sns_name }}] {{ place }} is updated"
        - |
          {{ place }} seems to be updated (or added a comment)!
          {% app_url_for('pc_frontend', route, true) %}

          {{ text }}
      ja_JP:
        - "[{{ op_config.sns_name }}] {{ place }} が更新されました"
        - |
          {{ place }} が更新されたか、コメントが追加されています。
          {% app_url_for('pc_frontend', route, true) %}

          {{ text }}
    variables:
      "op_config.sns_name": "SNS 名"
      route: "ルーティング"
      place: "場所"
      text: "テキスト"

mobile:
  updateNotification:
    caption: "Update Notification"
    configurable: false
    sample: 
      en:
        - "[{{ op_config.sns_name }}] {{ place }} is updated"
        - |
          {{ place }} seems to be updated (or added a comment)!
          {% app_url_for('mobile_frontend', route, true) %}

          {{ text }}
      ja_JP:
        - "[{{ op_config.sns_name }}] {{ place }} が更新されました"
        - |
          {{ place }} が更新されたか、コメントが追加されています。
          {% app_url_for('mobile_frontend', route, true) %}

          {{ text }}
    variables:
      "op_config.sns_name": "SNS 名"
      route: "ルーティング"
      place: "場所"
      text: "テキスト"

