options:
  charset: utf8

UpdateNotificationRequest:
  actAs: [Timestampable]
  columns:
    id: { type: integer(4), primary: true, autoincrement: true }
    target_route: { type: string(255), notnull: true }
    recipient_member_id: { type: integer(4), notnull: true }
  indexes:
    target_and_recipient_UNIQUE:
      fields: [target_route, recipient_member_id]
      type: unique
  options:
    type: MyISAM
    collate: utf8_unicode_ci
    charset: utf8

